export const TOGGLE_FILTER = "TOGGLE_FILTER";
export const SEARCH_GUEST = "SEARCH_GUEST";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const ADD_GUEST = "ADD_GUEST";
export const TOGGLE_ISCONFIRMED = 'TOGGLE_ISCONFIRMED'
